### ISSUE TITLE
Timeout Error with history.bulkWrite() Operation

### ISSUE THREAD

**Issue by ozenahmetcan** [ilovepixelart/ts-patch-mongoose#173]
I'm encountering a timeout error when attempting to use the patchHistoryPlugin in conjunction with Mongoose v7.5.0. The error occurs during the history.bulkWrite() operation, resulting in a timeout after 10 seconds.

**MySchema Example**

```
import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document } from 'mongoose';
import mongoose from 'mongoose';
import { patchHistoryPlugin } from 'ts-patch-mongoose';
import { EVENT } from '../constants/event';

@Schema({
  collection: 'definitions',
  timestamps: true,
  id: true,
  _id: true,
  toJSON: {
    virtuals: true,
    versionKey: false,
    transform: (doc, converted) => {
      delete converted._id;
    },
  },
})
export class Definition {
  @Prop({ type: mongoose.Schema.Types.ObjectId, auto: true })
  readonly _id: mongoose.Schema.Types.ObjectId;

  @Prop({ type: String })
  code: string;

  @Prop({ type: mongoose.Schema.Types.Mixed })
  value: any;
}

export type DefinitionDocument = Definition & Document;
export const DefinitionSchema = SchemaFactory.createForClass(Definition).plugin(patchHistoryPlugin, {
  eventCreated: EVENT.CREATED,
  eventUpdated: EVENT.UPDATED,
  eventDeleted: EVENT.DELETED,
  omit: ['__v'],
});

```
Error message: MongooseError: Operation `history.bulkWrite()` buffering timed out after 10000ms
   at Timeout.<anonymous> (/Users/ahmetcanozen/projects/mbys-main-service/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:186:23)
   at listOnTimeout (node:internal/timers:569:17)
   at processTimers (node:internal/timers:512:7)

- Node.js version: 18.17.1
- Mongoose version: 7.5.0

**Comment by ilovepixelart** [comment]
Hello @ozenahmetcan, thanks for reporting issue, form first glance looks like the issue is related to mongoose connection, error you posted simply means that mongoose tried to bulk write to collection history but after 10 sec gave up. This can be due to 2 factors, collection `history` failed to be registered/created on time (due to nest specific approach to mongoose) or there is general issue with connection to mongodb.

Let's approach this issue together, can you fork this https://github.com/ilovepixelart/ts-express-nest and add similar setup to what you trying to do currently then we can run same repo together and see same issue.

This plugin was intended to be used directly with mongoose
Working samples here: 
https://github.com/ilovepixelart/ts-express-swc
https://github.com/ilovepixelart/ts-express-esbuild

**Comment by brycelund** [comment]
Was there a solution this?
